### ISSUE TITLE
Question about image data format table

### ISSUE THREAD

**Issue by hugmouse** [Galaco/vtf#8]
I have a question about the values of some formats.

The fact is that for example the format `UVLX8888` in total has 32 bits, but if you take your code, then there should be 16 in total, am i right? Is there a multiplication by two somewhere?

Source: https://developer.valvesoftware.com/wiki/Valve_Texture_Format

------

| Format   | Red Bits | Green Bits | Blue Bits | Alpha Bits |  Total Bits |
|----------|----------|------------|-----------|------------|-------------|
| UVLX8888 | N/A      | N/A        | N/A       | N/A        | 32          |

https://github.com/Galaco/vtf/blob/3f0c638c8fe2ed6907e808127c2f232c7ba200fb/internal/mipmaps.go#L104-L106

------

| Format   | Red Bits | Green Bits | Blue Bits | Alpha Bits |  Total Bits |
|----------|----------|------------|-----------|------------|-------------|
| RGBA16161616F  | 16      | 16        | 16       | 16        | 64          |
| RGBA16161616  | 16      | 16        | 16       | 16        | 64          |

https://github.com/Galaco/vtf/blob/3f0c638c8fe2ed6907e808127c2f232c7ba200fb/internal/mipmaps.go#L100-L103

-----

| Format   | Red Bits | Green Bits | Blue Bits | Alpha Bits |  Total Bits |
|----------|----------|------------|-----------|------------|-------------|
| BGRX5551   | 5      | 5        | 5       | **1**        | 16          |

https://github.com/Galaco/vtf/blob/3f0c638c8fe2ed6907e808127c2f232c7ba200fb/internal/mipmaps.go#L88-L89

-----

And so on. Hope you get my point

**Comment by Galaco** [comment]
I’m not quite sure I understand you. The purpose of that function is to return the number of bytes required for a single pixel for a particular format, not the number of bits per color or pixel.

For each of those examples you provided as far as I am aware the sizes are correct (for example UVLX8888 is 32bits or 4 bytes as listed).

**Comment by hugmouse** [comment]
> 
> 
> I’m not quite sure I understand you. The purpose of that function is to return the number of bytes required for a single pixel for a particular format, not the number of bits per color or pixel.
> 
> For each of those examples you provided as far as I am aware the sizes are correct (for example UVLX8888 is 32bits or 4 bytes as listed).

I confused bits with bytes. Oh Lord. My mistake, sorry!
